[package]
name = "affs-read"
version = "0.3.2"
edition = "2024"
description = "A no_std compatible crate for reading Amiga Fast File System (AFFS) disk images"
documentation = "https://github.com/MuntasirSZN/affs-read"
license = "MIT"
keywords = ["adf", "affs", "amiga", "filesystem", "no_std"]
categories = ["embedded", "filesystem", "no-std", "parser-implementations"]

[[bench]]
harness = false
name = "checksums"

[[bench]]
harness = false
name = "hashing"

[dependencies]
memchr = { version = "2.7", default-features = false }
simdutf8 = { version = "0.1", default-features = false }

[dev-dependencies]
divan = "0.1"

[features]
default = ["std"]
alloc = []
std = []
